name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^8.0.0
  hive: ^4.0.0-dev.2
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  isar_flutter_libs: ^4.0.0-dev.13
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  supabase_flutter: ^2.7.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
